// chat/reflection/focusPlan.ts
// Version: 2026-02-21T00:00:00Z
// Purpose: Ephemeral guidance artifact generated by async reflection analysis.
// Stored separately from the reflection schema (Redis key per conversation + revision).

export type ReflectionFocusPlanV1 = {
  version: "v1"
  conversation_id: string
  episode_id?: string
  revision: number

  focus_fields: Array<{
    path: string
    reason: string
    priority: 1 | 2 | 3
  }>

  suggested_questions: Array<{
    field_path: string
    question: string
  }>

  constraints: {
    max_questions: 1 | 2 | 3
    avoid_repeat_within_turns: number
  }

  created_at: string
}

export function isReflectionFocusPlanV1(value: unknown): value is ReflectionFocusPlanV1 {
  if (typeof value !== "object" || value === null) return false
  const v = value as any
  if (v.version !== "v1") return false
  if (typeof v.conversation_id !== "string") return false
  if (typeof v.revision !== "number") return false
  if (!Array.isArray(v.focus_fields)) return false
  if (!Array.isArray(v.suggested_questions)) return false
  if (typeof v.constraints !== "object" || v.constraints === null) return false
  if (v.constraints.max_questions !== 1 && v.constraints.max_questions !== 2 && v.constraints.max_questions !== 3)
    return false
  if (typeof v.constraints.avoid_repeat_within_turns !== "number") return false
  if (typeof v.created_at !== "string") return false
  return true
}
